
benchmark: 'basic'

basic:
  name: basic
  nrange: [20, 50, 100, 180, 400, 600, 900, 1200]
  solver: gurobi
  apis: ['linopy', 'jump', 'pyomo', 'cvxpy', 'pulp', 'gurobipy', 'solver']

knapsack:
  name: knapsack
  nrange: [10, 50, 100]
  solver: gurobi
  apis: ['linopy', 'jump', 'pyomo', 'cvxpy', 'pulp', 'gurobipy', 'solver']
